config/routes.rb
ChancesR::Application.routes.draw do
  
  resources :binomials

  resources :poissons

  root 'welcome#index'

end

app/models/binomial.rb
class Binomial < ActiveRecord::Base
	validates :trials, presence: true
	validates :successes, presence: true
	validates :chances, presence: true

	def factorial(x)
		return (1..x).inject(:*)
	end

	def combinations(n, x)
		return factorial(n) / (factorial(n - x) * factorial(x))
	end

	def Binomial_Probability()
		return combinations(trials, successes) * (chances ** successes) * ((1 - chances) ** (trials - successes))
	end

	def Cumulative_Probability()
		total = 0
		(1..successes).each do |s|
			totals += combinations(trials, successes) * (chances ** successes) * ((1 - chances) ** (trials - successes))
			return total
		end
	end
end

app/models/poisson.rb
class Poisson < ActiveRecord::Base
	validates :occurances, presence: true
	validates :lambda, presence: true

	def factorial(x)
		return (1..x).inject(:*)
	end

	def poisson_distribution()
		return (lambda ** occurances) / (((2.71828) ** lambda) * factorial(occurances))
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/binomials_controller.rb
class BinomialsController < ApplicationController
  def new
  	@binomial = Binomial.new
  end

  def create
  	@binomial = Binomial.new(binomial_params)
    if Binomial.count > 5
      @old_binomial = Binomial.first
      @old_binomial.destroy
    end

  	if @binomial.save
  		redirect_to @binomial
  	else
      flash[:notice] = "You have blank fields. "
  		render 'new'
  	end
  end

  def show
  	@binomial = Binomial.find(params[:id])
  end

  def index
  	@binomials = Binomial.all
  end

  private
  	def binomial_params
  		params.require(:binomial).permit(:trials, :successes, :chances)
  	end
end

app/controllers/poissons_controller.rb
class PoissonsController < ApplicationController
  def new
  	@poisson = Poisson.new
  end

  def create
	@poisson = Poisson.new(poisson_params)
    if Poisson.count > 5
      @old_poisson = Poisson.first
      @old_poisson.destroy
    end

  	if @poisson.save
  	  redirect_to @poisson
  	else
      flash[:notice] = "You have blank fields. "
  	  render 'new'
  	end
  end

  def show
  	@poisson = Poisson.find(params[:id])
  end

  def index
  	@poissons = Poisson.all
  end

  private
  	def poisson_params
  		params.require(:poisson).permit(:occurances, :lambda)
  	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/binomial_helper.rb
module BinomialHelper
end

app/helpers/poisson_helper.rb
module PoissonHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/binomials/_form.html.erb
<%= form_for :binomial, url: binomials_path do |b| %>
	<% if @binomial.errors.any? %>
	  	<div id="error_explanation">
    		<h2><%= pluralize(@binomial.errors.count, "error") %> prohibited
      			this answer from being saved:</h2>
    		<ul>
    			<% @binomial.errors.full_messages.each do |msg| %>
      				<li><%= msg %></li>
    			<% end %>
    		</ul>
  		</div>
  	<% end %>
	<p>
		<%= b.label :trials %><br>
		<%= b.number_field :trials %>
	</p>
	<p>
		<%= b.label :successes %><br>
		<%= b.number_field :successes %>
	</p>
	<p>
		<%= b.label :chances %><br>
		<%= b.number_field :chances %>
	</p>
	<p>
		<%= b.submit %>
	</p>
<% end %>

app/views/binomials/edit.html.erb
<h1>Binomial#edit</h1>
<p>Find me in app/views/binomial/edit.html.erb</p>

app/views/binomials/index.html.erb
<h1>Binomial Distribution</h1>

<h1>Listing answers</h1>
 
<table>
  <tr>
    <th>Trials</th>
    <th>Successes</th>
    <th>Chances</th>
    <th>Binomial Probability</th>
    <th>Cumulative Probability</th>
  </tr>
 
  <% @binomials.each do |b| %>
    <tr>
      <td><%= b.trials %></td>
      <td><%= b.successes %></td>
      <td><%= b.chances %></td>
      <td><%= b.Binomial_Probability() %></td>
      <td><!--%= b.Cumulative_Probability() %--></td>
    </tr>
  <% end %>
</table>

app/views/binomials/new.html.erb
<h1>New Binomial</h1>

<%= render 'form' %>

app/views/binomials/show.html.erb
<h1>Binomial#show</h1>

<%= @binomial.Binomial_Probability() %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChancesR</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/poissons/_form.html.erb
<%= form_for :poisson, url: poissons_path do |b| %>
	<% if @poisson.errors.any? %>
	  	<div id="error_explanation">
    		<h2><%= pluralize(@poisson.errors.count, "error") %> prohibited
      			this answer from being saved:</h2>
    		<ul>
    			<% @poisson.errors.full_messages.each do |msg| %>
      				<li><%= msg %></li>
    			<% end %>
    		</ul>
  		</div>
  	<% end %>
	<p>
		<%= b.label :occurances %><br>
		<%= b.number_field :occurances %>
	</p>
	<p>
		<%= b.label :lambda %><br>
		<%= b.number_field :lambda %>
	</p>
	<p>
		<%= b.submit %>
	</p>
<% end %>

app/views/poissons/index.html.erb
<h1>Poisson Distribution</h1>

<h1>Listing answers</h1>
 
<table>
  <tr>
    <th>Occurances</th>
    <th>Average</th>
    <th>Poisson Probability</th>
  </tr>
 
  <% @poissons.each do |p| %>
    <tr>
      <td><%= p.occurances %></td>
      <td><%= p.lambda %></td>
      <td><%= p.Poisson_Probability() %></td>
    </tr>
  <% end %>
</table>

app/views/poissons/new.html.erb
<h1>New Poisson</h1>

<%= render 'form' %>

app/views/poissons/show.html.erb
<h1>Poisson#show</h1>

<%= @poisson.poisson_distribution() %> 

app/views/welcome/index.html.erb
<h1>ChancesR</h1>
<p>A Probability App!</p>

<%= link_to "Binomial", new_binomial_path %><br>
<p></p>
<%= link_to "Poisson", new_poisson_path %>